/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.interfaz;

/**
 *
 * @author serxa
 */
public class Tablero extends javax.swing.JFrame {

    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Casilla1 = new javax.swing.JButton();
        Casilla22 = new javax.swing.JButton();
        Casilla29 = new javax.swing.JButton();
        Casilla36 = new javax.swing.JButton();
        Casilla8 = new javax.swing.JButton();
        Casilla15 = new javax.swing.JButton();
        Casilla2 = new javax.swing.JButton();
        Casilla3 = new javax.swing.JButton();
        Casilla4 = new javax.swing.JButton();
        Casilla5 = new javax.swing.JButton();
        Casilla6 = new javax.swing.JButton();
        Casilla7 = new javax.swing.JButton();
        Casilla9 = new javax.swing.JButton();
        Casilla10 = new javax.swing.JButton();
        Casilla11 = new javax.swing.JButton();
        Casilla12 = new javax.swing.JButton();
        Casilla13 = new javax.swing.JButton();
        Casilla14 = new javax.swing.JButton();
        Casilla21 = new javax.swing.JButton();
        Casilla20 = new javax.swing.JButton();
        Casilla19 = new javax.swing.JButton();
        Casilla18 = new javax.swing.JButton();
        Casilla17 = new javax.swing.JButton();
        Casilla16 = new javax.swing.JButton();
        Casilla23 = new javax.swing.JButton();
        Casilla24 = new javax.swing.JButton();
        Casilla25 = new javax.swing.JButton();
        Casilla26 = new javax.swing.JButton();
        Casilla27 = new javax.swing.JButton();
        Casilla28 = new javax.swing.JButton();
        Casilla42 = new javax.swing.JButton();
        Casilla41 = new javax.swing.JButton();
        Casilla40 = new javax.swing.JButton();
        Casilla39 = new javax.swing.JButton();
        Casilla38 = new javax.swing.JButton();
        Casilla37 = new javax.swing.JButton();
        Casilla35 = new javax.swing.JButton();
        Casilla34 = new javax.swing.JButton();
        Casilla33 = new javax.swing.JButton();
        Casilla30 = new javax.swing.JButton();
        Casilla31 = new javax.swing.JButton();
        Casilla32 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Casilla1.setBackground(new java.awt.Color(255, 255, 255));
        Casilla1.setForeground(new java.awt.Color(0, 0, 0));
        Casilla1.setText("CQMa1");
        Casilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla1ActionPerformed(evt);
            }
        });
        getContentPane().add(Casilla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 193, -1, -1));

        Casilla22.setBackground(new java.awt.Color(255, 255, 255));
        Casilla22.setForeground(new java.awt.Color(0, 0, 0));
        Casilla22.setText("CQAm22");
        Casilla22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla22ActionPerformed(evt);
            }
        });
        getContentPane().add(Casilla22, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        Casilla29.setBackground(new java.awt.Color(255, 255, 255));
        Casilla29.setForeground(new java.awt.Color(0, 0, 0));
        Casilla29.setText("CQRo29");
        getContentPane().add(Casilla29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 80, -1));

        Casilla36.setBackground(new java.awt.Color(255, 255, 255));
        Casilla36.setForeground(new java.awt.Color(0, 0, 0));
        Casilla36.setText("CQVe36");
        getContentPane().add(Casilla36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 325, 80, 30));

        Casilla8.setBackground(new java.awt.Color(255, 255, 255));
        Casilla8.setForeground(new java.awt.Color(0, 0, 0));
        Casilla8.setText("CQAz8");
        getContentPane().add(Casilla8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        Casilla15.setBackground(new java.awt.Color(255, 255, 255));
        Casilla15.setForeground(new java.awt.Color(0, 0, 0));
        Casilla15.setText("CQNa15");
        getContentPane().add(Casilla15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        Casilla2.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla amarilla.jpg")); // NOI18N
        Casilla2.setText("jButton8");
        getContentPane().add(Casilla2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 175, 50, 20));

        Casilla3.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla3.setText("jButton9");
        Casilla3.setPreferredSize(new java.awt.Dimension(50, 25));
        Casilla3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla3ActionPerformed(evt);
            }
        });
        getContentPane().add(Casilla3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 155, 50, 20));

        Casilla4.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla naranja.jpg")); // NOI18N
        Casilla4.setText("jButton10");
        getContentPane().add(Casilla4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 135, 50, 20));

        Casilla5.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla verde.jpg")); // NOI18N
        Casilla5.setText("jButton11");
        getContentPane().add(Casilla5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 115, 50, 20));

        Casilla6.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla6.setText("jButton12");
        getContentPane().add(Casilla6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 50, 20));

        Casilla7.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla rosa.jpg")); // NOI18N
        Casilla7.setText("jButton13");
        getContentPane().add(Casilla7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 75, 50, 20));

        Casilla9.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla rosa.jpg")); // NOI18N
        Casilla9.setText("jButton14");
        Casilla9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla9ActionPerformed(evt);
            }
        });
        getContentPane().add(Casilla9, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 30, 50, 20));

        Casilla10.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla10.setText("jButton15");
        getContentPane().add(Casilla10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 50, 20));

        Casilla11.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla amarilla.jpg")); // NOI18N
        Casilla11.setText("jButton16");
        getContentPane().add(Casilla11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 50, 20));

        Casilla12.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla marron.jpg")); // NOI18N
        Casilla12.setText("jButton17");
        getContentPane().add(Casilla12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 50, 20));

        Casilla13.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla13.setText("jButton18");
        getContentPane().add(Casilla13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 50, 20));

        Casilla14.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla verde.jpg")); // NOI18N
        Casilla14.setText("jButton19");
        getContentPane().add(Casilla14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 50, 20));

        Casilla21.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla marron.jpg")); // NOI18N
        Casilla21.setText("jButton20");
        getContentPane().add(Casilla21, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 50, 20));

        Casilla20.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla20.setText("jButton21");
        getContentPane().add(Casilla20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 50, 20));

        Casilla19.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla azul.jpg")); // NOI18N
        Casilla19.setText("jButton22");
        Casilla19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casilla19ActionPerformed(evt);
            }
        });
        getContentPane().add(Casilla19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 50, 20));

        Casilla18.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla rosa.jpg")); // NOI18N
        Casilla18.setText("jButton23");
        getContentPane().add(Casilla18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 50, 20));

        Casilla17.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla17.setText("jButton24");
        getContentPane().add(Casilla17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 50, 20));

        Casilla16.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla verde.jpg")); // NOI18N
        Casilla16.setText("jButton25");
        getContentPane().add(Casilla16, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 50, 20));

        Casilla23.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla marron.jpg")); // NOI18N
        Casilla23.setText("jButton1");
        getContentPane().add(Casilla23, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 50, 20));

        Casilla24.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla24.setText("jButton2");
        getContentPane().add(Casilla24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 50, 20));

        Casilla25.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla verde.jpg")); // NOI18N
        Casilla25.setText("jButton3");
        getContentPane().add(Casilla25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 50, 20));

        Casilla26.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla naranja.jpg")); // NOI18N
        Casilla26.setText("jButton4");
        getContentPane().add(Casilla26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 50, 20));

        Casilla27.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla27.setText("jButton5");
        getContentPane().add(Casilla27, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 50, 20));

        Casilla28.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla azul.jpg")); // NOI18N
        Casilla28.setText("jButton6");
        getContentPane().add(Casilla28, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 50, 20));

        Casilla42.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla amarilla.jpg")); // NOI18N
        Casilla42.setText("jButton7");
        getContentPane().add(Casilla42, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 216, 50, 20));

        Casilla41.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla41.setText("jButton26");
        getContentPane().add(Casilla41, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 234, 50, 20));

        Casilla40.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla rosa.jpg")); // NOI18N
        Casilla40.setText("jButton27");
        getContentPane().add(Casilla40, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 252, 50, 20));

        Casilla39.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla azul.jpg")); // NOI18N
        Casilla39.setText("jButton28");
        getContentPane().add(Casilla39, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 270, 50, 20));

        Casilla38.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla38.setText("jButton29");
        getContentPane().add(Casilla38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 288, 50, 20));

        Casilla37.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla naranja.jpg")); // NOI18N
        Casilla37.setText("jButton30");
        getContentPane().add(Casilla37, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 306, 50, 20));

        Casilla35.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla naranja.jpg")); // NOI18N
        Casilla35.setText("jButton31");
        getContentPane().add(Casilla35, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 354, 50, 20));

        Casilla34.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla34.setText("jButton32");
        getContentPane().add(Casilla34, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 375, 50, 20));

        Casilla33.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla amarilla.jpg")); // NOI18N
        Casilla33.setText("jButton33");
        getContentPane().add(Casilla33, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 50, 20));

        Casilla30.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla azul.jpg")); // NOI18N
        Casilla30.setText("jButton34");
        getContentPane().add(Casilla30, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 354, 50, 20));

        Casilla31.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla blanca.jpg")); // NOI18N
        Casilla31.setText("jButton35");
        getContentPane().add(Casilla31, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 375, 50, 20));

        Casilla32.setIcon(new javax.swing.ImageIcon("C:\\Users\\serxa\\OneDrive\\Documentos\\NetBeansProjects\\PRO_Proyecto_2ev\\Media\\casilla marron.jpg")); // NOI18N
        Casilla32.setText("jButton36");
        getContentPane().add(Casilla32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 50, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Casilla22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Casilla22ActionPerformed

    private void Casilla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Casilla1ActionPerformed

    private void Casilla9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Casilla9ActionPerformed

    private void Casilla3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Casilla3ActionPerformed

    private void Casilla19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casilla19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Casilla19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Casilla1;
    private javax.swing.JButton Casilla10;
    private javax.swing.JButton Casilla11;
    private javax.swing.JButton Casilla12;
    private javax.swing.JButton Casilla13;
    private javax.swing.JButton Casilla14;
    private javax.swing.JButton Casilla15;
    private javax.swing.JButton Casilla16;
    private javax.swing.JButton Casilla17;
    private javax.swing.JButton Casilla18;
    private javax.swing.JButton Casilla19;
    private javax.swing.JButton Casilla2;
    private javax.swing.JButton Casilla20;
    private javax.swing.JButton Casilla21;
    private javax.swing.JButton Casilla22;
    private javax.swing.JButton Casilla23;
    private javax.swing.JButton Casilla24;
    private javax.swing.JButton Casilla25;
    private javax.swing.JButton Casilla26;
    private javax.swing.JButton Casilla27;
    private javax.swing.JButton Casilla28;
    private javax.swing.JButton Casilla29;
    private javax.swing.JButton Casilla3;
    private javax.swing.JButton Casilla30;
    private javax.swing.JButton Casilla31;
    private javax.swing.JButton Casilla32;
    private javax.swing.JButton Casilla33;
    private javax.swing.JButton Casilla34;
    private javax.swing.JButton Casilla35;
    private javax.swing.JButton Casilla36;
    private javax.swing.JButton Casilla37;
    private javax.swing.JButton Casilla38;
    private javax.swing.JButton Casilla39;
    private javax.swing.JButton Casilla4;
    private javax.swing.JButton Casilla40;
    private javax.swing.JButton Casilla41;
    private javax.swing.JButton Casilla42;
    private javax.swing.JButton Casilla5;
    private javax.swing.JButton Casilla6;
    private javax.swing.JButton Casilla7;
    private javax.swing.JButton Casilla8;
    private javax.swing.JButton Casilla9;
    // End of variables declaration//GEN-END:variables
}
